[[EXPLAIN-extra]]
= extra

== using where
在过滤出来的行使用where条件过滤，往往和 `type` 关联,需要综合判断，例如  type= All 代表全表扫描，往往需要优化。

常见优化方案是 在where 列添加 索引；

== using index
SQL所需要返回的所有列数据均在一棵索引树上，而无需访问实际的行记录。 这类SQL语句往往性能较好

== using index condition
确实命中了索引，但不是返回的所有的列数据都在索引树上，还需要访问实际的行记录进行显示非索引字段。

== using filesort
得到所需结果集，需要对所有记录进行文件排序, 这类SQL语句性能极差，需要进行优化。

典型的，在一个没有建立索引的列上进行了order by，就会触发filesort，常见的优化方案是，在order by的列上添加索引，
避免每次查询都全量排序

MySQL将需要做一个额外的传递，以找出如何检索排好序的行。排序是通过根据连接类型遍历所有行，并存储匹配WHERE的所有行的排序键+指针来完成的。然后对键进行排序。最后以排序的顺序检索行。

== using Temporary
需要建立临时表(temporary table)来暂存中间结果。 这类SQL语句性能较低，往往也需要进行优化。

典型的，group by和order by同时存在，且作用于不同的字段时，就会建立临时表，以便计算出最终的结果集

== Using join buffer (Block Nested Loop)
嵌套循环计算.这类SQL语句性能往往也较低，需要进行优化。

典型的，两个关联表join，关联字段均未建立索引，就会出现这种情况。常见的优化方案是，在关联字段上添加索引，避免每次嵌套循环计算


==  Distinct
在找到第一个匹配的行之后，MySQL 将不会继续搜索符合当前条件的更多行。

==  Not exists
MySQL 能够对查询进行 LEFT JOIN 优化，并且在找到一行符合 LEFT JOIN 条件之后，不会继续搜索符合条件的更多行
[example]
.例如
====
[source,sql]
----
SELECT * FROM t1 LEFT JOIN t2 ON t1.id=t2.id WHERE t2.id IS NULL;
----
假设 t2.id 定义为 not null。在这种情况下，MySQL 将扫描 t1并查找 t2到 t1.id 中的行。如果 MySQL 在 t2中找到匹配的行，它就知道 t2.id 永远不能为 NULL，并且不会扫描 t2中具有相同 id 的其余行。换句话说，对于 t1中的每一行，MySQL 只需要在 t2中执行一次查找，与 t2中有多少匹配行无关。
====

== range checked for each record (index map: #)
MySQL没有找到一个真正好的索引来使用。相反，它将对前面表中的每个行组合检查要使用哪个索引(如果有的话)，并使用这个索引从表中检索行。这不是非常快，但比在没有索引的情况下进行连接要快

