= asciidoc 教程文档
:!version-label:
:idprefix:
:idseparator: -
:toc: left
:toclevels: 4
:tabsize: 4
:numbered:
:sectanchors:
:sectnums:
:hide-uri-scheme:
:docinfo: shared,private
:attribute-missing: warn
:chomp: default headers packages
:spring-boot-artifactory-repo: snapshot
:github-tag: main
:icons: font

== 关于本文档

本教程文档建议使用 https://github.com/asciidoctor/asciidoctor-gradle-plugin[asciidoctor-gradle-plugin]来编译构建。具体构建过程脚本参见 link:build.gradle[]

    ../gradlew asciidoctor

本地环境构建需要安装 ruby2.5+， 使用 gem 管理模块包。

其它依赖：

. 本教程目前使用了 “asciidoctor-diagram”， "asciidoctor-kroki"， "asciidoctor-chart" 三个图表模块;
. https://github.com/spring-io/spring-asciidoctor-extensions[spring-asciidoctor-extensions扩展插件]来支持 tab切换，
. tocify.js 来支持目录收缩。

== 语法简易指南

AsciiDoc 是一种文本文档格式，用于编写笔记、文档、文章、书籍、电子书、幻灯片、网页、手册页和博客。AsciiDoc 文件可以翻译成多种格式，包括 HTML、PDF、EPUB、手册页。

具体语法指南详见  xref:src/docs/tutorial.adoc[asciidoc 语法指南]

== 图表

目前 asciidoc 图表可采用 “asciidoctor-diagram”， "asciidoctor-kroki"， "asciidoctor-chart" 三种插件， 具体教程详见  xref:src/docs/diagram/README.adoc[asciidoctor 图表教程]


== 转换文档

目前有 `asciidoctor` 和 `gradle-plugin` 两种方式可以将源文件（ `.adoc` ）转为 html 或者 pdf.


===  Asciidoctor

. 要转换 asciidoc 文件，您需要安装 Asciidoctor gem。

 gem install  asciidoctor

. 如果您希望能够创建 pdf 文件，您可以使用 asciidoctor-pdf gem。

 gem install --pre asciidoctor-pdf

==== 用法

include::useage.adoc[]

==== pdf 乱码问题

include::src/docs/tutorial.adoc[tags=asciidoctor-pdf]

=== gradle plugin

todo...


[source,xml,indent=0,role="primary"]
.Maven
----
<dependency>
    <groupId>com.example</groupId>
    <artifactId>some-library</artifactId>
    <version>1.2.3</version>
</dependency>
----

[source,indent=0,role="secondary"]
.Gradle
----
compile 'com.example:some-library:1.2.3'
----
