
= Kafka如何实现高吞吐量低延迟

> https://www.pixelstech.net/article/1552056773-How-Kafka-achieves-high-throughput-low-latency[原文]

Kafka 是一个高吞吐量、低延迟的消息流系统。它被许多大公司广泛采用。一个配置良好的Kafka集群可以达到百万并发写入的超高吞吐量。Kafka 如何做到这一点？这篇文章将尝试解释 Kafka 使用的一些技术。



== 页缓存+磁盘顺序写入 -- 生产

Kafka 每次收到一条记录，最终都会将其写入磁盘文件。但是如果每次收到一条记录都写入磁盘，则性能不会很好。事实上，Kafka在这方面有一个很棒的设计，那就是它利用了**操作系统的页面缓存**。

操作系统具有称为页面缓存的L1 缓存，它是内存中的缓存。也可以称为OS缓存，由操作系统管理的缓存::
. 将记录写入磁盘时，可以直接写入OS缓存，即写入内存。
. 下一个操作系统将决定何时将操作系统缓存中的记录写入磁盘。

这一步会大大提高写入速度，因为它确实是将数据写入内存而不是直接写入磁盘。

数据写入的另一个关键部分是Kafka按顺序将数据写入文件，这意味着它不会随机访问文件并在随机位置写入。**通常随机访问磁盘中的文件很慢**。

基于这两种方式，Kafka在写入数据时实现了**高吞吐量**

== 零拷贝 -- 消费

有些消费者会消费来自 Kafka 的数据，这实际上是从存储数据的磁盘文件中读取数据，然后将其发送到下游。这整个过程将包括几个步骤。

. 它检查数据是否在操作系统缓存中，如果没有，它将从磁盘中读取并将其放入操作系统缓存中
. 将数据从操作系统缓存复制到应用程序缓存
. 将数据从应用程序缓存复制到操作系统套接字缓存
. 套接字缓存数据发送到网络网关
. 发送给下游消费者的数据

NOTE: 其实第2步和第3步是可以去掉的。这两个步骤需要时间，因为数据需要从一个地方复制到另一个地方，而且操作系统也需要在这个过程中切换上下文。因此Kafka采用了所谓的零拷贝技术来省去这两个步骤。

它的作用是将操作系统缓存中的数据直接发送到网关，然后再发送到下游。套接字缓存将包含的只是数据的描述符，而不是实际数据。由于此过程不涉及数据拷贝，故称为零拷贝。

如果你注意上面的步骤，你也会发现如果操作系统缓存中有很多数据，就不需要那么频繁地读取磁盘文件。这将进一步提高读取性能。
